CREATE TABLE users(
    id INT AUTO_INCREMENT PRIMARY KEY, 
    uid VARCHAR(255) NOT NULL, 
    name VARCHAR(255) NOT NULL, 
    email VARCHAR(255) UNIQUE NOT NULL, 
    phone VARCHAR(20), 
    password VARCHAR(255) NOT NULL, 
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP, 
    last_login DATETIME
);
