name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cleanup of port 8084
        run: |
          docker stop smart_helmet || true
          docker rm -f smart_helmet || true
          docker network prune -f || true

      - name: Clean old JAR files
        run: |
          rm -f target/*.jar || true

      - name: Build with Maven
        run: mvn clean package -DskipTests -T 2C --file pom.xml

      - name: Build Docker image
        run: |
          docker image prune -f || true
          docker build -t smart_helmet .

      - name: Final aggressive cleanup
        run: |
          docker stop smart_helmet || true
          docker rm -f smart_helmet || true
          docker system prune -f || true
          docker network prune -f || true

      - name: Start container with memory+swap limits and auto-restart
        run: |
          docker run -d \
            --name smart_helmet \
            -p 8084:8084 \
            --restart=always \
            --memory="3g" \
            --memory-swap="8g" \
            -e JAVA_OPTS="-Xms3g -Xmx8g -XX:+UseG1GC -XX:MaxGCPauseMillis=100" \
            smart_helmet

  verify-deployment:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    steps:
      - name: Wait for application startup
        run: sleep 5

      - name: Verify deployment health
        run: |
          echo "🔍 Checking if application is responding from external endpoint..."
          
          # Wait for application to be ready (up to 3 minutes)
          for i in {1..3}; do
            if curl -f https://examspace.shubhodip.in/actuator/health 2>/dev/null; then
              echo "✅ Application is healthy and responding from external endpoint!"
              break
            else
              echo "⏳ Waiting for application to respond... (attempt $i/3)"
              sleep 15
            fi
          done
          
          # Final comprehensive health check
          if curl -f https://examspace.shubhodip.in/actuator/health; then
            echo "✅ Final health check passed - Application is fully operational!"
          else
            echo "❌ Final health check failed - Application may not be accessible"
            exit 1
          fi